<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Errors;

use Screenshothis\Screenshothis\Utils;
/** ForbiddenException - Quota exceeded */
class ForbiddenException
{
    /**
     *
     * @var string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    public string $error;

    /**
     *
     * @var string $requestId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('requestId')]
    public string $requestId;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  string  $error
     * @param  string  $requestId
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(string $error, string $requestId, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->error = $error;
        $this->requestId = $requestId;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): ForbiddenExceptionThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new ForbiddenExceptionThrowable($message, (int) $code, $this);
    }
}