<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Errors;

use Screenshothis\Screenshothis\Models\Operations;
use Screenshothis\Screenshothis\Utils;
/** NotReadyException - Service is not ready */
class NotReadyException
{
    /**
     *
     * @var Operations\StatusNotReady $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Screenshothis\Screenshothis\Models\Operations\StatusNotReady')]
    public Operations\StatusNotReady $status;

    /**
     *
     * @var string $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public string $timestamp;

    /**
     *
     * @var string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    public string $error;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  Operations\StatusNotReady  $status
     * @param  string  $timestamp
     * @param  string  $error
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(Operations\StatusNotReady $status, string $timestamp, string $error, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->status = $status;
        $this->timestamp = $timestamp;
        $this->error = $error;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): NotReadyExceptionThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new NotReadyExceptionThrowable($message, (int) $code, $this);
    }
}