<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


declare(strict_types=1);

namespace Screenshothis\Screenshothis\Hooks;

use Screenshothis\Screenshothis\SDKConfiguration;

interface SDKInitHook
{
    public function sdkInit(SDKConfiguration $config): SDKConfiguration;
}
