workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Screenshothis-OAS:
        inputs:
            - location: https://api.screenshothis.com/openapi
        registry:
            location: registry.speakeasyapi.dev/danestves-llc/screenshothis/screenshothis-oas
targets:
    screenshothis:
        target: php
        source: Screenshothis-OAS
        publish:
            packagist:
                username: $packagist_username
                token: $packagist_token
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/danestves-llc/screenshothis/screenshothis-oas-php-code-samples
            labelOverride:
                fixedValue: PHP (SDK)
            blocking: false
