<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Operations;


/** Types of web resources that can be blocked during screenshot capture */
enum BlockResource: string
{
    case Document = 'document';
    case Stylesheet = 'stylesheet';
    case Image = 'image';
    case Media = 'media';
    case Font = 'font';
    case Script = 'script';
    case Texttrack = 'texttrack';
    case Xhr = 'xhr';
    case Fetch = 'fetch';
    case Prefetch = 'prefetch';
    case Eventsource = 'eventsource';
    case Websocket = 'websocket';
    case Manifest = 'manifest';
    case Signedexchange = 'signedexchange';
    case Ping = 'ping';
    case Cspviolationreport = 'cspviolationreport';
    case Preflight = 'preflight';
    case Other = 'other';
}
