<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Operations;


/** Output image format. JPEG offers smaller file sizes, PNG supports transparency, WebP provides modern compression. */
enum Format: string
{
    case Jpeg = 'jpeg';
    case Png = 'png';
    case Webp = 'webp';
}
