<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Operations;


/** LiveResponseBody - Service is alive */
class LiveResponseBody
{
    /**
     *
     * @var StatusAlive $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Screenshothis\Screenshothis\Models\Operations\StatusAlive')]
    public StatusAlive $status;

    /**
     *
     * @var string $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public string $timestamp;

    /**
     * @param  StatusAlive  $status
     * @param  string  $timestamp
     * @phpstan-pure
     */
    public function __construct(StatusAlive $status, string $timestamp)
    {
        $this->status = $status;
        $this->timestamp = $timestamp;
    }
}