<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Operations;


/** Accessibility setting to reduce animations and transitions for motion-sensitive users */
enum PrefersReducedMotion: string
{
    case NoPreference = 'no-preference';
    case Reduce = 'reduce';
}
