<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Operations;


/** Set the preferred color scheme for websites that support dark/light mode theming */
enum PrefersColorScheme: string
{
    case Light = 'light';
    case Dark = 'dark';
}
