<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Operations;

use Screenshothis\Screenshothis\Utils\SpeakeasyMetadata;
class TakeScreenshotRequest
{
    /**
     *
     * @var string $apiKey
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=api_key')]
    public string $apiKey;

    /**
     *
     * @var string $url
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=url')]
    public string $url;

    /**
     *
     * @var ?string $blockRequests
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=block_requests')]
    public ?string $blockRequests = null;

    /**
     * $blockResources
     *
     * @var ?array<BlockResource> $blockResources
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=block_resources')]
    public ?array $blockResources = null;

    /**
     *
     * @var ?string $cacheKey
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cache_key')]
    public ?string $cacheKey = null;

    /**
     *
     * @var ?string $headers
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=headers')]
    public ?string $headers = null;

    /**
     *
     * @var ?string $cookies
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cookies')]
    public ?string $cookies = null;

    /**
     *
     * @var ?string $selector
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=selector')]
    public ?string $selector = null;

    /**
     * Output image format. JPEG offers smaller file sizes, PNG supports transparency, WebP provides modern compression.
     *
     * @var ?Format $format
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=format')]
    public ?Format $format = null;

    /**
     *
     * @var ?float $quality
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=quality')]
    public ?float $quality = null;

    /**
     * Set the preferred color scheme for websites that support dark/light mode theming
     *
     * @var ?PrefersColorScheme $prefersColorScheme
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=prefers_color_scheme')]
    public ?PrefersColorScheme $prefersColorScheme = null;

    /**
     * Accessibility setting to reduce animations and transitions for motion-sensitive users
     *
     * @var ?PrefersReducedMotion $prefersReducedMotion
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=prefers_reduced_motion')]
    public ?PrefersReducedMotion $prefersReducedMotion = null;

    /**
     *
     * @var ?float $cacheTtl
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cache_ttl')]
    public ?float $cacheTtl = null;

    /**
     *
     * @var ?float $width
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=width')]
    public ?float $width = null;

    /**
     *
     * @var ?float $height
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=height')]
    public ?float $height = null;

    /**
     *
     * @var ?bool $isMobile
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=is_mobile')]
    public ?bool $isMobile = null;

    /**
     *
     * @var ?bool $isLandscape
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=is_landscape')]
    public ?bool $isLandscape = null;

    /**
     *
     * @var ?bool $hasTouch
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=has_touch')]
    public ?bool $hasTouch = null;

    /**
     *
     * @var ?float $deviceScaleFactor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=device_scale_factor')]
    public ?float $deviceScaleFactor = null;

    /**
     *
     * @var ?bool $blockAds
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=block_ads')]
    public ?bool $blockAds = null;

    /**
     *
     * @var ?bool $blockCookieBanners
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=block_cookie_banners')]
    public ?bool $blockCookieBanners = null;

    /**
     *
     * @var ?bool $blockTrackers
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=block_trackers')]
    public ?bool $blockTrackers = null;

    /**
     *
     * @var ?bool $isCached
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=is_cached')]
    public ?bool $isCached = null;

    /**
     *
     * @var ?bool $bypassCsp
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=bypass_csp')]
    public ?bool $bypassCsp = null;

    /**
     * @param  string  $apiKey
     * @param  string  $url
     * @param  ?Format  $format
     * @param  ?float  $quality
     * @param  ?string  $blockRequests
     * @param  ?array<BlockResource>  $blockResources
     * @param  ?PrefersColorScheme  $prefersColorScheme
     * @param  ?PrefersReducedMotion  $prefersReducedMotion
     * @param  ?float  $cacheTtl
     * @param  ?string  $cacheKey
     * @param  ?string  $headers
     * @param  ?string  $cookies
     * @param  ?string  $selector
     * @param  ?float  $width
     * @param  ?float  $height
     * @param  ?bool  $isMobile
     * @param  ?bool  $isLandscape
     * @param  ?bool  $hasTouch
     * @param  ?float  $deviceScaleFactor
     * @param  ?bool  $blockAds
     * @param  ?bool  $blockCookieBanners
     * @param  ?bool  $blockTrackers
     * @param  ?bool  $isCached
     * @param  ?bool  $bypassCsp
     * @phpstan-pure
     */
    public function __construct(string $apiKey, string $url, ?string $blockRequests = null, ?array $blockResources = null, ?string $cacheKey = null, ?string $cookies = null, ?string $selector = null, ?Format $format = Format::Jpeg, ?float $quality = 80, ?PrefersColorScheme $prefersColorScheme = PrefersColorScheme::Light, ?PrefersReducedMotion $prefersReducedMotion = PrefersReducedMotion::NoPreference, ?float $cacheTtl = 3600, ?float $width = 1920, ?float $height = 1080, ?bool $isMobile = false, ?bool $isLandscape = false, ?bool $hasTouch = false, ?float $deviceScaleFactor = 1, ?bool $blockAds = false, ?bool $blockCookieBanners = false, ?bool $blockTrackers = false, ?bool $isCached = false, ?bool $bypassCsp = false, ?string $headers = null)
    {
        $this->apiKey = $apiKey;
        $this->url = $url;
        $this->blockRequests = $blockRequests;
        $this->blockResources = $blockResources;
        $this->cacheKey = $cacheKey;
        $this->headers = $headers;
        $this->cookies = $cookies;
        $this->selector = $selector;
        $this->format = $format;
        $this->quality = $quality;
        $this->prefersColorScheme = $prefersColorScheme;
        $this->prefersReducedMotion = $prefersReducedMotion;
        $this->cacheTtl = $cacheTtl;
        $this->width = $width;
        $this->height = $height;
        $this->isMobile = $isMobile;
        $this->isLandscape = $isLandscape;
        $this->hasTouch = $hasTouch;
        $this->deviceScaleFactor = $deviceScaleFactor;
        $this->blockAds = $blockAds;
        $this->blockCookieBanners = $blockCookieBanners;
        $this->blockTrackers = $blockTrackers;
        $this->isCached = $isCached;
        $this->bypassCsp = $bypassCsp;
    }
}