<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Components;


class Check
{
    /**
     * Name of the health check
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Status of the health check
     *
     * @var CheckStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Screenshothis\Screenshothis\Models\Components\CheckStatus')]
    public CheckStatus $status;

    /**
     * Duration of the health check in milliseconds
     *
     * @var ?float $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $duration = null;

    /**
     * Detailed information about the health check
     *
     * @var ?array<string, mixed> $details
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('details')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $details = null;

    /**
     * Error message if the health check failed
     *
     * @var ?string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $error = null;

    /**
     * @param  string  $name
     * @param  CheckStatus  $status
     * @param  ?float  $duration
     * @param  ?array<string, mixed>  $details
     * @param  ?string  $error
     * @phpstan-pure
     */
    public function __construct(string $name, CheckStatus $status, ?float $duration = null, ?array $details = null, ?string $error = null)
    {
        $this->name = $name;
        $this->status = $status;
        $this->duration = $duration;
        $this->details = $details;
        $this->error = $error;
    }
}