<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Components;


/** Status of the health check */
enum CheckStatus: string
{
    case Pass = 'pass';
    case Fail = 'fail';
}
