<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis\Models\Components;


/** HealthCheck - Performs a comprehensive health check of all critical system components including database connectivity, storage availability, job queue status, and S3 functionality. Returns detailed status information for monitoring and alerting systems. */
class HealthCheck
{
    /**
     * Overall health status of the system
     *
     * @var Status $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Screenshothis\Screenshothis\Models\Components\Status')]
    public Status $status;

    /**
     * Timestamp of the health check
     *
     * @var string $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public string $timestamp;

    /**
     * Uptime of the service in seconds
     *
     * @var float $uptime
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('uptime')]
    public float $uptime;

    /**
     * Array of health check results
     *
     * @var array<Check> $checks
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('checks')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Screenshothis\Screenshothis\Models\Components\Check>')]
    public array $checks;

    /**
     * Application version or commit hash
     *
     * @var ?string $version
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('version')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $version = null;

    /**
     * @param  Status  $status
     * @param  string  $timestamp
     * @param  float  $uptime
     * @param  array<Check>  $checks
     * @param  ?string  $version
     * @phpstan-pure
     */
    public function __construct(Status $status, string $timestamp, float $uptime, array $checks, ?string $version = null)
    {
        $this->status = $status;
        $this->timestamp = $timestamp;
        $this->uptime = $uptime;
        $this->checks = $checks;
        $this->version = $version;
    }
}