<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis;

use Screenshothis\Screenshothis\Utils\Retry;

/**
 * ScreenshothisBuilder is used to configure and build an instance of the SDK.
 */
class ScreenshothisBuilder
{
    public function __construct(
        private SDKConfiguration $sdkConfig = new SDKConfiguration(),
    ) {
    }

    /**
     * setClient allows setting a custom Guzzle client for the SDK to make requests with.
     *
     * @param  \GuzzleHttp\ClientInterface  $client
     * @return ScreenshothisBuilder
     */
    public function setClient(\GuzzleHttp\ClientInterface $client): ScreenshothisBuilder
    {
        $this->sdkConfig->client = $client;

        return $this;
    }

    /**
     * setServerUrl is used to configure the server URL for the SDK, and optionally template any parameters in the URL.
     *
     * @param  string  $serverUrl
     * @param  array<string, string>  $params
     * @return ScreenshothisBuilder
     */
    public function setServerUrl(string $serverUrl, ?array $params = null): ScreenshothisBuilder
    {
        $this->sdkConfig->serverUrl = Utils\Utils::templateUrl($serverUrl, $params);

        return $this;
    }

    /**
     * setServer is used to configure the server for the SDK
     *
     * @param  int  $serverIdx
     * @return ScreenshothisBuilder
     */
    public function setServerIndex(int $serverIdx): ScreenshothisBuilder
    {
        $this->sdkConfig->serverIndex = $serverIdx;

        return $this;
    }

    public function setRetryConfig(Retry\RetryConfig $config): ScreenshothisBuilder
    {
        $this->sdkConfig->retryConfig = $config;

        return $this;
    }

    /**
     * build is used to build the SDK with any of the configured options.
     *
     * @return Screenshothis
     */
    public function build(): Screenshothis
    {
        if ($this->sdkConfig->client === null) {
            $this->sdkConfig->client = new \GuzzleHttp\Client([
                'timeout' => 60,
            ]);
        }

        return new Screenshothis($this->sdkConfig);
    }
}