<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Screenshothis\Screenshothis;



/** Screenshothis - Screenshothis API: API designed to take screenshots of websites */
class Screenshothis
{
    public const SERVERS = [
        /** Production Server */
        'https://api.screenshothis.com',
    ];

    public Screenshots $screenshots;

    public Health $health;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return ScreenshothisBuilder
     */
    public static function builder(): ScreenshothisBuilder
    {
        return new ScreenshothisBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->screenshots = new Screenshots($this->sdkConfiguration);
        $this->health = new Health($this->sdkConfiguration);
        $this->initHooks();

    }

    private function initHooks(): void
    {
        $this->sdkConfiguration = $this->sdkConfiguration->hooks->sdkInit($this->sdkConfiguration);
    }
}